name: Deploy html to ec2
on:
  push:
    branches:
        -main
jobs:
    deploy:
      runs-on: ubuntu-latest

      steps: 
        -name: Checkout code
        -uses: actions/checkout@v4

        -name: Show all files
        -run: ls -al
